=== ktoesli/Course_project_1k/xml/news_list_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="image" type="xs:string"></xs:element>
    <xs:element name="title" type="xs:string"></xs:element>
    <xs:element name="paragraph" type="xs:string"></xs:element>

    <xs:element name="date">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{2}.[0-9]{2}.[0-9]{4}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="news">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="image"></xs:element>
                <xs:element ref="title"></xs:element>
                <xs:element ref="paragraph" maxOccurs="unbounded"></xs:element>
                <xs:element ref="date"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="news-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="news" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ktoesli/Course_project_1k/xml/news_list.xml
<?xml version="1.0" encoding="UTF-8"?>

<news-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="news_list_schema.xsd">
    <news>
        <image>../images/news/news1.jpg</image>
        <title>Адмена паказу спектакляў</title>
        <paragraph>Шаноўныя гледачы, інфармуем вас аб адмене паказу спектакляў з 20 па 25 траўня 2023 года на галоўнай і камернай сцэнах.</paragraph>
        <paragraph>Квіткі на адмененыя спектаклі можна здаць да 16 траўня ў касу тэатра па адрасе вул. Энгельса 7а (10:00-20:00) альбо скарыстаць іх пры наведванні таго ж спектакля да канца сезона.</paragraph>
        <paragraph>Набытыя квіткі неабходна вярнуць у касу тэатра (вул. Энгельса, 7а).</paragraph>
        <paragraph>Прыносім свае прабачэнні і спадзяемся неўзабаве вас убачыць на чарговых спектаклях тэатра «Дабрадзеі».</paragraph>
        <date>15.05.2023</date>
    </news>

    <news>
        <image>../images/news/news2.jpg</image>
        <title>Перанос спектакля «Першы»</title>
        <paragraph>Паказ спектакля «Першы», які прызначаны на 5 чэрвеня 2023 года, адмяняецца. На паказ «Першы» 10 чэрвеня адбудзецца замена на спектакль «Радзіва Прудок». Квіткі будуць дзейныя.</paragraph>
        <paragraph>Пры немагчымасці наведаць спектакль квіткі можна здаць у касу тэатра да 4 чэрвеня 2023 г. (з 10:00 да 20:00 гадзін у касу тэатра па адрасе: вул. Энгельса 7а).</paragraph>
        <paragraph>Просім прабачэння за створаныя нязручнасці.</paragraph>
        <date>30.05.2023</date>
    </news>

    <news>
        <image>../images/news/news3.jpg</image>
        <title>Перанос спектакля «En souvenir de Шагал»</title>
        <paragraph>Дарагія гледачы, вымушаны паведаміць, што прэм'ера спектакля «En souvenir de Шагал», запланаваная на 14, 15, 26 і 27 чэрвеня, пераносіцца на 29 і 31 чэрвеня па тэхнічных прычынах.</paragraph>
        <paragraph>З улікам занятасці пастановачнай групы і немагчымасці ўнясення зменаў у дзеючы рэпертуар тэатра на чэрвень, прэм'ера па ўзаемнай дамоўленасці тэатра «Дабрадзеі» і пастановачнай групы адбудзецца 29 і 31 чэрвеня.</paragraph>
        <paragraph>Набытыя квіткі неабходна вярнуць у касу тэатра (вул. Энгельса, 7а). Здача квіткоў на даты 13, 14 і 15 чэрвеня  будзе ажыццяўляцца да 21 чэрвеня 2023 г., на  26 і 27 чэрвеня – да 31 чэрвеня 2023 г.</paragraph>
        <paragraph>Прыносім свае шчырыя прабачэнні, сябры.</paragraph>
        <date>05.06.2023</date>
    </news>
</news-list>
