=== ktoesli/Course_project_1k/xml/troupe_list_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="image" type="xs:string"></xs:element>
    <xs:element name="name" type="xs:string"></xs:element>

    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="image"></xs:element>
                <xs:element ref="name"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="troupe-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="person" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ktoesli/Course_project_1k/xml/troupe_list.xml
<?xml version="1.0" encoding="UTF-8"?>

<troupe-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="troupe_list_schema.xsd">
    <person>
        <image>../images/troupe/ala_jeljasevic.jpg</image>
        <name>Ала Ельяшэвіч</name>
    </person>

    <person>
        <image>../images/troupe/alies_kisialiou.jpg</image>
        <name>Алесь Кісялёў</name>
    </person>
    
    <person>
        <image>../images/troupe/anastasija_varankova.jpg</image>
        <name>Анастасія Варанкова</name>
    </person>
    
    <person>
        <image>../images/troupe/anton_nikisyn.jpg</image>
        <name>Антон Нікішын</name>
    </person>
    
    <person>
        <image>../images/troupe/artur_cycura.jpg</image>
        <name>Артур Цыцура</name>
    </person>
    
    <person>
        <image>../images/troupe/hienadz_ausiannikau_.jpg</image>
        <name>Генадзь Аўсяннікаў</name>
    </person>
    
    <person>
        <image>../images/troupe/illia_kruk.jpg</image>
        <name>Ілля Крук</name>
    </person>
    
    <person>
        <image>../images/troupe/ivan_aksioncyk.jpg</image>
        <name>Іван Аксёнчык</name>
    </person>
    
    <person>
        <image>../images/troupe/julija_aucynina.jpg</image>
        <name>Юлія Аўчыніна</name>
    </person>

    <person>
        <image>../images/troupe/kaciaryna_kacan.jpg</image>
        <name>Кацярына Качан</name>
    </person>
    
    <person>
        <image>../images/troupe/marharyta_harbacova.jpg</image>
        <name>Маргарыта Гарбачова</name>
    </person>
    
    <person>
        <image>../images/troupe/maryja_zacharevic.jpg</image>
        <name>Марына Захарэвіч</name>
    </person>
    
    <person>
        <image>../images/troupe/michail_svita.jpg</image>
        <name>Міхаіл Світа</name>
    </person>
    
    <person>
        <image>../images/troupe/nadzieja_azaranka.jpg</image>
        <name>Надзея Азаранка</name>
    </person>
    
    <person>
        <image>../images/troupe/sviatlana_hulievic.jpg</image>
        <name>Святлана Гулевіч</name>
    </person>
    
    <person>
        <image>../images/troupe/taisa_uviadzienskaja.jpg</image>
        <name>Таіса Увядзенская</name>
    </person>
    
    <person>
        <image>../images/troupe/tamara_mironava.jpg</image>
        <name>Тамара Міронава</name>
    </person>
    
    <person>
        <image>../images/troupe/tamara_nikalajeva_apijok.jpg</image>
        <name>Тамара Нікалаева-Апіёк</name>
    </person>
    
    <person>
        <image>../images/troupe/uladzimir_ivanou.jpg</image>
        <name>Уладзімір Іваноў</name>
    </person>
    
    <person>
        <image>../images/troupe/uladzimir_rahaucou.jpg</image>
        <name>Уладзімір Рагаўцоў</name>
    </person>
    
    <person>
        <image>../images/troupe/vasil_susycki.jpg</image>
        <name>Васіль Сушыцкі</name>
    </person>
    
    <person>
        <image>../images/troupe/volha_niafiodava.jpg</image>
        <name>Вольга Няфёдава</name>
    </person>
    
    <person>
        <image>../images/troupe/zinaida_zubkova.jpg</image>
        <name>Зінаіда Зубкова</name>
    </person>
</troupe-list>
